version: '3.9'

services:
  order-system-modular-monolith.api:
    image: ${DOCKER_REGISTRY-}ordersystemmodularmonolithapi
    build:
      context: .
      dockerfile: order-system-modular-monolith.Api/Dockerfile
    container_name: orders-api
    depends_on:
      - redis
      - postgres
      - mongo
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__Redis: redis:6379
      ConnectionStrings__Postgres: Host=postgres;Port=5432;Database=ordersdb;Username=postgres;Password=postgres
      ConnectionStrings__Mongo: mongodb://mongo:27017/orders-mongo
      Services__Product: http://orders-api:8080
      Services__Stock: http://orders-api:8080
      Jwt__Authority: "http://orders-api:8080"
      Jwt__Audience: "order-system-modular-monolith"
    ports:
      - "5000:8080"
    networks:
      - orders-network

  redis:
    image: redis:7
    container_name: redis
    volumes:
      - redis-data:/data
    networks:
      - orders-network

  postgres:
    image: postgres:16
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - orders-network


  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@local.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - "5050:80"
    depends_on:
      - postgres
    networks:
      - orders-network

  mongo:
    image: mongo:7
    container_name: mongo
    volumes:
      - mongo-data:/data/db
    networks:
      - orders-network

  # --- Monitoring ---
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - orders-network

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3000:3000"
    depends_on:
      - prometheus
      - loki
    volumes:
      - grafana-data:/var/lib/grafana
    networks:
      - orders-network

  # --- Tracing ---
  jaeger:
    image: jaegertracing/all-in-one
    container_name: jaeger
    ports:
      - "16686:16686"   # Jaeger UI
      - "6831:6831/udp" # UDP agent
      - "4317:4317"     # OTLP gRPC
    networks:
      - orders-network

  # --- Logging ---
  loki:
    image: grafana/loki
    container_name: loki
    ports:
      - "3100:3100"
    volumes:
      - ./monitoring/loki-config.yml:/etc/loki/local-config.yaml
      - loki-data:/loki
    command: -config.file=/etc/loki/local-config.yaml
    networks:
      - orders-network

volumes:
  redis-data:
  postgres-data:
  mongo-data:
  grafana-data:
  loki-data: 

networks:
  orders-network:
    driver: bridge