<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<RootNamespace>order_system_modular_monolith.BuildingBlocks</RootNamespace>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Duende.IdentityServer" Version="7.*" />
		<PackageReference Include="Duende.IdentityServer.AspNetIdentity" Version="7.*" />
		<PackageReference Include="Duende.IdentityServer.EntityFramework" Version="7.*" />
		<PackageReference Include="Humanizer.Core" Version="2.14.1" />
		<PackageReference Include="MediatR" Version="14.0.0" />
		<PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="10.0.3" />
		<PackageReference Include="Microsoft.AspNetCore.Hosting.Abstractions" Version="2.3.9" />
		<PackageReference Include="Microsoft.AspNetCore.Http" Version="2.3.9" />
		<PackageReference Include="Microsoft.AspNetCore.Mvc.Core" Version="2.3.9" />

		<PackageReference Include="Microsoft.EntityFrameworkCore" Version="10.0.3" />

		<PackageReference Include="Microsoft.EntityFrameworkCore.Relational" Version="10.0.3" />

		<PackageReference Include="Microsoft.Extensions.Caching.StackExchangeRedis" Version="10.0.3" />
		<PackageReference Include="Microsoft.Extensions.Configuration" Version="10.0.1" />
		<PackageReference Include="MongoDB.Bson" Version="3.6.0" />
		<PackageReference Include="MongoDB.Driver" Version="3.6.0" />
		<PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="10.0.0" />
		<PackageReference Include="Scrutor" Version="7.0.0" />
		<PackageReference Include="StackExchange.Redis" Version="2.9.32" />
	</ItemGroup>

	<ItemGroup>
	  <Folder Include="Redis\" />
	</ItemGroup>

</Project>
